// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpkogupeanqhhwujvkxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impwa29ndXBlYW5xaGh3dWp2a3hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTgxMTQsImV4cCI6MjA2OTQ3NDExNH0.GX3opA_f2NbKBKBA_kKFLFfutV1z9its4WtSbhIZYHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});